FeatureFlagsDemo/Models/ErrorViewModel.cs
namespace FeatureFlagsDemo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FeatureFlagsDemo/Models/FeatureFlags.cs
namespace FeatureFlagsDemo.Models
{
    public enum FeatureFlags
    {
        MobileReview,
        MobileDetailedReview
    }
}

FeatureFlagsDemo/Models/Mobile.cs
namespace FeatureFlagsDemo.Models
{
    public class Mobile
    {
        public string? Id { set; get; }
        public string? Name { set; get; }
        public string? Specfication { set; get; }
        public MobileReview? ReviewDetails { set; get; }
    }
}

FeatureFlagsDemo/Models/MobileReview.cs
namespace FeatureFlagsDemo.Models
{
    public class MobileReview
    {
        public string? Rating { set; get; }
        public string? Remarks { set; get; }
    }
}

FeatureFlagsDemo/Controllers/HomeController.cs
using FeatureFlagsDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement;
using System.Diagnostics;

namespace FeatureFlagsDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IFeatureManager _featureManager;

        public HomeController(ILogger<HomeController> logger, IFeatureManager featureManager)
        {
            _logger = logger;
            _featureManager = featureManager;
        }

        public async Task<IActionResult> Index()
        {
            if (await _featureManager.IsEnabledAsync(nameof(FeatureFlags.MobileReview)))
            {
                ViewData["WelcomeMessage"] = "Welcome - Mobile Review Application";
            }
            else
            {
                ViewData["WelcomeMessage"] = "Welcome";
            }

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FeatureFlagsDemo/Controllers/MobileController.cs
using FeatureFlagsDemo.Interfaces;
using FeatureFlagsDemo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.FeatureManagement.Mvc;

namespace FeatureFlagsDemo.Controllers
{
    [Authorize]
    [FeatureGate(nameof(FeatureFlags.MobileReview))]
    public class MobileController : Controller
    {
        private readonly IMobileDataService _mobileDataService;

        public MobileController(IMobileDataService mobileDataService)
        {
            _mobileDataService = mobileDataService;
        }

        public IActionResult Index()
        {
            List<Mobile> mobiles = _mobileDataService.GetAllMobileReviews();
            return View(mobiles);
        }

        [FeatureGate(nameof(FeatureFlags.MobileDetailedReview))]
        public IActionResult ReviewDetails(string? id)
        {
            Mobile? mobile = _mobileDataService.GetAllMobileReviews().Find(p => p.Id.Equals(id));
            return View(mobile);
        }
    }
}

FeatureFlagsDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["WelcomeMessage"]</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FeatureFlagsDemo/Views/Mobile/Index.cshtml
@model List<Mobile>
@{
    ViewData["Title"] = "View All Mobiles Review";
}
<h1>@ViewData["Title"]</h1>

<table class="table table-responsive table-hover">
    <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Specification</td>
        <td>Rating</td>
        <td>Review Details</td>
    </tr>
    @foreach (Mobile mobile in Model)
    {
        <tr>
            <td>@mobile.Id</td>
            <td>@mobile.Name</td>
            <td>@mobile.Specfication</td>
            <td>@mobile.ReviewDetails?.Rating</td>
            <td>
                <feature name="@nameof(FeatureFlags.MobileDetailedReview)">
                    @Html.ActionLink("Click Here", "ReviewDetails", new { id = mobile.Id })
                </feature>
            </td>
        </tr>
    }
</table>

FeatureFlagsDemo/Views/Mobile/ReviewDetails.cshtml
@model Mobile
@{
    ViewData["Title"] = "Mobile Detailed Review";
}
<h1>@ViewData["Title"]</h1>

<br />

<table class="table table-responsive table-hover">
    <tr>
        <td><span style="font-weight:bold">Id</span></td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Name</span></td>
        <td>@Model.Name</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Specfications</span></td>
        <td>@Model.Specfication</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Rating</span></td>
        <td>@Model.ReviewDetails?.Rating</td>
    </tr>
    <tr>
        <td><span style="font-weight:bold">Review</span></td>
        <td>@Model.ReviewDetails?.Remarks</td>
    </tr>
</table>

FeatureFlagsDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FeatureFlagsDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FeatureFlagsDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FeatureFlagsDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <feature name="@nameof(FeatureFlags.MobileReview)">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Mobile" asp-action="Index">Mobile Reviews</a>
                            </li>
                        </feature>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - FeatureFlagsDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>